# Generated by Django 3.2.16 on 2024-03-21 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0002_videos'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoProb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('video_file', models.FileField(upload_to='videoprob/')),
            ],
        ),
        migrations.DeleteModel(
            name='Videos',
        ),
    ]
