# Generated by Django 4.1.7 on 2024-03-30 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0003_auto_20240321_2349'),
    ]

    operations = [
        migrations.RenameField(
            model_name='videoprob',
            old_name='video_file',
            new_name='videos_file',
        ),
    ]
